[tool.poetry]
name = "nonebot-plugin-majsoul"
version = "0.0.2"
description = ""
authors = ["ssttkkl <huang.wen.long@hotmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
packages = [
    { include = "nonebot_plugin_majsoul", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.9"
nonebot2 = "^2.0.0rc1"
nonebot-adapter-onebot = "^2.1.5"
tzlocal = "^4.2"
httpx = "^0.23.0"
pydantic = "^1.10.2"
monthdelta = "^0.9.1"
icmplib = "^3.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
